# Generated by Django 2.2 on 2023-05-04 18:29

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20230503_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, unique=True),
            preserve_default=False,
        ),
    ]
