# Generated by Django 2.2 on 2023-05-04 18:45

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_auto_20230504_1843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(default=uuid.uuid1, unique=True),
        ),
    ]
